<!-- Inside the same XML file -->
<?xml version="1.0" encoding="UTF-8"?>
<!-- Declares document type and defines allowed elements/structure -->
<!DOCTYPE library [
    
    <!-- The root element <library> contains one or more <book> elements -->
    <!ELEMENT library (book+)>

    <!-- A <book> element must contain <title>, <author>, <year> in order -->
    <!ELEMENT book (title, author, year)>
    
    <!-- Each of the following tags only contains text (PCDATA = text) -->
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    
    <!-- This declares an attribute 'id' for <book>, it must be given (REQUIRED) -->
    <!ATTLIST book id CDATA #REQUIRED>
]>

<!-- Actual XML data starts here -->
<library>
    <!-- Book 1 with id attribute and 3 child elements -->
    <book id="B101">
        <title>The Alchemist</title>
        <author>Paulo Coelho</author>
        <year>1988</year>
    </book>

    <!-- Book 2 -->
    <book id="B102">
        <title>Wings of Fire</title>
        <author>A.P.J. Abdul Kalam</author>
        <year>1999</year>
    </book>
</library>
